version: '3'

services:
  app:
    build:
      context: ./docker/go
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ".:/var/www/revel"
    ports:
      - 9000:9000
    links:
      - mysql

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    env_file:
      - ./docker/mysql/env
    ports:
      - 3308:3306
    volumes:
      - revel_app_db:/var/lib/mysql

volumes:
  revel_app_db:
    name: revel_app_db
